# use Yarn Modern by default
yarnPath: ".yarn/releases/yarn-berry.cjs"

# let's do backward-compartibility with v1 and npmjs people
# see https://yarnpkg.com/features/pnp#compatibility-table
nodeLinker: node-modules
