name: "Dockerfile CI"

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test builds
        run: docker build . -t madebythepinshub/dogehouse-snap-dl-api
